version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: secure-password-manager-db
    restart: always
    environment:
      POSTGRES_USER: secure_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: secure_password_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local